### ISSUE TITLE
Want problems on DataStructures

### ISSUE THREAD

**Issue by shivajipotnuru** [shivajipotnuru/Java-Interview-Problems#4]
wanted good DS problems which are frequently asked in the interview.

**Comment by parzuko** [comment]
Hey can i take this? I'll add 3-4 popular interview questions(with the solutions).

**Comment by shivajipotnuru** [comment]
> Hey can i take this? I'll add 3-4 popular interview questions(with the solutions).

Yeah please proceed:)

**Comment by saiharsha-22** [comment]
@shivajipotnuru Can I add sorting algorithms with code and time complexity in a separate folder?

**Comment by khushbu014** [comment]
Can you assign this to me , will add some popular interview questions and their solutions.
